name: untitled
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  flutter_screenutil: ^5.9.3
  gap: ^3.0.1
  google_fonts: ^6.3.2
  url_launcher: ^6.3.2
  webview_flutter: ^4.13.0
  supabase_flutter: ^2.5.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  google_sign_in: ^6.1.5
  flutter_facebook_auth: ^6.0.3
  flutter_svg: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/Frame.png"

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/icons/

  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Light.otf
          weight: 300
        - asset: assets/fonts/Satoshi-LightItalic.otf
          weight: 300
          style: italic
        - asset: assets/fonts/Satoshi-Regular.otf
          weight: 400
        - asset: assets/fonts/Satoshi-Italic.otf
          weight: 400
          style: italic
        - asset: assets/fonts/Satoshi-Medium.otf
          weight: 500
        - asset: assets/fonts/Satoshi-MediumItalic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/Satoshi-Bold.otf
          weight: 700
        - asset: assets/fonts/Satoshi-BoldItalic.otf
          weight: 700
          style: italic
        - asset: assets/fonts/Satoshi-Black.otf
          weight: 900
        - asset: assets/fonts/Satoshi-BlackItalic.otf
          weight: 900
          style: italic
